# Public configuration for open-source finance assistant

# Market Data APIs
alpha_vantage_key: "demo" # Public test key
yahoo_finance_source: "yfinance"

# Embeddings
embedding_model: "all-MiniLM-L6-v2"
vector_db: "FAISS"

# LLM
language_model: "mistralai/Mistral-7B-Instruct-v0.1"

# STT and TTS
stt_engine: "whisper-base"
tts_engine: "pyttsx3"

# Other settings
retrieval_top_k: 3
